# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
permissions:
  contents: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 */1 * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
      - name: Run Update Python Script
        run: |
          python update_blogPost.py
      - name: Update README.md file
        run: |
          git pull
          git add .
          git diff
          git config --local user.email "a01049048063@gmail.com"
          git config --local user.name "yunhobb"
          git commit -m "Update README.md"
          git push
